### ISSUE TITLE
Linux packaging besides .deb?

### ISSUE THREAD

**Issue by rosswmerrifield** [tigerconnect/desktop-app#3]
It's cool you guys have a Linux version at all, most companies don't even bother but I'm on an RPM based distro so the .deb release won't work for me. Can we get an alternate packaging of TigerConnect desktop for Linux? .rpm would be convenient for me (and Red Hat Linux is "enterprisey" so maybe it makes sense for you?), but an AppImage or even just a tarbar with the binaries would work too. I get it you can't support every Linux packaging format, there are way too many.  But please consider something more universal than a .deb file. Even a progressive web app would be nice for the non-Debian/Ubuntu Linux users.

I appreciate the consideration.

Ross

**Comment by tt-mikeolson** [comment]
Hi Ross,

Thanks for the feedback. We've made an RPM build for the latest TigerConnect Desktop App v5.4.2 available here, and plan to continue supporting it going forward in new releases: https://github.com/tigerconnect/desktop-app/releases/download/v5.4.2/TigerConnect-latest.rpm . We've tested it on Fedora.

Feel free to let us know how that's working for you.

**Comment by rosswmerrifield** [comment]
Awesome! Can confirm it's working here on Fedora 38. Thanks :+1:
